Add `toBigNumberString` and `E`
EdgeApp/biggystring pull request #18
Opened 2023-09-07 21:42 UTC by samholmes

### CHANGELOG

- added: New `toBigNumberString` function to convert JS number to big number strings
- added: New `E` function for scientific notation (i.e. `123e4` is `E(123, 4)`)

### Dependencies

 none

### Description

 none

2023-09-08 19:26 UTC, samholmes reviewed
from review-bar with paul

2023-09-08 19:26 UTC, samholmes commented on src/index.ts
> +const EXPO_REGEX = /e((?:\+|-)\d+)$/
call this `SCI_NOTATION_REGEX`.

2023-09-08 19:26 UTC, samholmes commented on src/index.ts
> +function E(x1: string, exponent: number): string {
Don't export this one. Name it `sciNotation`

2023-09-08 19:26 UTC, samholmes commented on src/index.ts
> +function toBigNumberString(n: number | string): string {
Change `toBns(n: number | string)`.

Add a `fixSciNotation` which does the sci-notation part and use that on all string inputs for each function that  deals with a BNS

2023-11-09 23:07 UTC, paullinator requested changes

2023-11-09 23:07 UTC, paullinator commented on src/index.ts
> +    const base = out.replace(SCI_NOTATION_REGEX, '')
Replace with regex with `SCI_NOTATION_REGEX = /(.[0-9]*)e((?:\+|-)\d+)$/` Then you only have to apply it once to get both the exponent and base.

2023-11-14 00:18 UTC, paullinator requested changes

2023-11-14 00:18 UTC, paullinator commented on src/index.ts
> +  console.log(x1, exponent)
stray log

2023-11-14 00:18 UTC, paullinator commented on test/biggystring.test.ts
> +  it('scientific notation: big negative numbers', function () {
I still feel like this needs more tests. 

Checking decimal values like `3.1234e12` `.001e12` `0.000123e12`

invalid values like `3.1.0e123` `3x0e12` `

2023-11-14 00:21 UTC, paullinator requested changes
more tests

2023-11-17 01:10 UTC, paullinator requested changes
One more small change and we're good. new tests look great.

2023-11-17 01:10 UTC, paullinator commented on src/index.ts
> +  validate(out)
This is redundant for most operations since they already call validate. Create a toBnsInner that gets used by other ops.

2023-11-17 06:18 UTC, paullinator approved these changes

2023-12-05 19:31 UTC, merged